Dockerfile: bump to Go 1.13 for errors.Is()
We revendored kubernetes, so now we need 1.13

vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is