Fixes thread safety with LB healthcheck
Maps for endpoints and services may be accessed at the same time because
the services and endpoints handlers are attached to two different
informer goroutines. This can cause:

fatal error: concurrent map read and map write

goroutine 322 [running]:
 runtime.throw(0x1b2bac6, 0x21)
 /usr/lib/golang/src/runtime/panic.go:1117 +0x72 fp=0xc000811b60 sp=0xc000811b30 pc=0x43e612
 runtime.mapaccess2(0x18e4000, 0xc0018c5e90, 0xc000811bf0, 0x2921980, 0x0)
 /usr/lib/golang/src/runtime/map.go:469 +0x255 fp=0xc000811ba0 sp=0xc000811b60 pc=0x415c55

 github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*loadBalancerHealthChecker).AddEndpoints(0xc0018c5ef0, 0xc0004d9180)
 /go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/healthcheck.go:
  github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*gateway).AddEndpoints(...)
 /go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway.go:107

Signed-off-by: Tim Rozet <trozet@redhat.com>
(cherry picked from commit 915c779a0f20d7754d742d86363b575283d48bbd)