Kind Updates > Update kubernetes version in the files below:     github/workflows/test.xml     contrib/kind-common     test/scripts/upgrade-ovn.sh     test/scripts/install-kind.sh     docs/installation/launching-ovn-kubernetes-on-kind.md     docs/developer-guide/local_testing_guide.md
> Update golangci-lint and golangci-lint-action in .github/workflows/test.xml

> Fix:
  # golang.org/x/tools/internal/tokeninternal
  Error: /home/runner/go/pkg/mod/golang.org/x/tools@v0.16.1/internal/tokeninternal/tokeninternal.go:78:9: invalid array length -delta * delta (constant -256 of type int64)
  this error occurs because some dependencies are incompatible with go1.25:
  1.in "coredns-ocp-dnsnameresolver/operator" CONTROLLER_TOOLS_VERSION=v0.14.0 isn't compatible with go1.25, specify CONTROLLER_TOOLS_VERSION=v0.19.0 in kind-common
  2.in kind-common install_metallb() controller_gen_version = "v0.16.3" isn't compatible with go1.25, upgrade to controller_gen_version = "v0.19.0"

Signed-off-by: Meina-rh <meinli@redhat.com>