[UDN: host isolation]: fix lint
Fix issue introduced in 3275d498b4026609effbaaf88a88ff6e43819ad5

$ make lint
...
level=info msg="[linters_context/goanalysis] analyzers took 4m3.270244378s with top 10 stages: buildir: 2m29.130860339s, nilness: 5.955006101s, printf: 3.859331341s, fact_deprecated: 3.799388364s, ctrlflow: 3.482855272s, inspect: 3.316943625s, fact_purity: 2.391957936s, S1038: 2.121120295s, gofmt: 2.089813745s, unused: 2.075213702s"
pkg/node/base_node_network_controller_dpu.go:1: : # github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node [github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.test]
pkg/node/udn_isolation_test.go:364:52: not enough arguments in call to NewUDNHostIsolationManager
        have (bool, bool, "k8s.io/client-go/informers/core/v1".PodInformer)
        want (bool, bool, "k8s.io/client-go/informers/core/v1".PodInformer, string, record.EventRecorder) (typecheck)
package node

Signed-off-by: Flavio Fernandes <ffernandes@nvidia.com>